### ISSUE TITLE
single-node does not create directories

### ISSUE THREAD

**Issue by mdanil007** [tolstoyevsky/cusdeb-single-node#11]
On the first build single-node does not create directories dominion-workspace and blackmagic-workspace.

**Comment by eugulixes** [comment]
I came across the problem some time ago, but now I can't reproduce it. @polina-popova, @denismosolov, are you able to reproduce the issue?

**Comment by polina-popova** [comment]
For me it is not relevant for now.

**Comment by denismosolov** [comment]
I'm unable to reproduce
