### ISSUE TITLE
Error in running install

### ISSUE THREAD

**Issue by MatteoGheza** [tolstoyevsky/cusdeb-single-node#54]
There is an error in bitbucket git clone function. The bitbucket' s repos not found

**Comment by eugulixes** [comment]
Hello @MatteoGheza 
Thank you for the report. Currently, two CusDeb components are published in the _private_ Bitbucket repor, so this is the main reason why you cannot clone the repos. Our main goal is to open all the CusDeb services and components in the nearest future.

**Comment by MatteoGheza** [comment]
Thanks
